name: Check Historical Stdlib Generator

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  check_hsg:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          # version: '1'
          version: 'nightly'
      - uses: julia-actions/cache@v3
      - run: julia --color=yes .ci/check_hsg.jl
      # When the check fails, the regenerated file is what the tree should contain.
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: version_map
          path: src/version_map.jl
