name: Update Historical Stdlibs

on:
  workflow_dispatch:

permissions: # Permissions for the `GITHUB_TOKEN` token
  contents: write
  pull-requests: write

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  run_hsg:
    name: Update Historical Stdlibs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          # version: '1'
          version: 'nightly'
      - uses: julia-actions/cache@v2
      - name: "Instantiate the project"
        run: julia --color=yes --project=ext/HistoricalStdlibGenerator -e 'import Pkg; Pkg.instantiate()'
      - name: "Run the `generate_historical_stdlibs.jl` script"
        run: julia --threads=auto --color=yes --project=ext/HistoricalStdlibGenerator ext/HistoricalStdlibGenerator/generate_historical_stdlibs.jl
      - run: git status
      - run: git add -A
      - run: git diff HEAD
      - name: "Create or update the pull request"
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "bot/update-historical-stdlibs"
          delete-branch: true
          commit-message: "🤖 Update the list of historical stdlibs"
          title: "🤖 Update the list of historical stdlibs"
          body: |
            This PR updates the list of historical stdlibs.
            Note: CI will not automatically run on this PR. To run CI, please
            close and reopen the PR.
            @staticfloat please take a look
